### ISSUE TITLE
No updates of podcasts since 2 days

### ISSUE THREAD

**Issue by maxol18** [i3arnon/YouCast#57]
Hi,

Since 2 days suddenly the podcast are not updating.

**Comment by mrDLSable** [comment]
Are you using your own API key? If not, please follow the steps in the readme document to set your own API key.
________________________________
Van: maxol18 <notifications@github.com>
Verzonden: donderdag 11 juni 2020 07:37
Aan: i3arnon/YouCast <YouCast@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [i3arnon/YouCast] No updates of podcasts since 2 days (#57)


Hi,

Since 2 days suddenly the podcast are not updating.

**Comment by maxol18** [comment]
Hi,

Yes i use my onw key ans i user version 2.12

**Comment by maxol18** [comment]
Hi,

I have updated my key.

It is now working

best regards

**Comment by maxol18** [comment]
I have updated my key.
